"""add roles table

Revision ID: b67df9778128
Revises: 0ec6d92f163c
Create Date: 2026-08-05 10:22:26.742261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b67df9778128"
down_revision: Union[str, Sequence[str], None] = "0ec6d92f163c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("can_view_warehouse", sa.Boolean(), nullable=False),
        sa.Column(
            "can_manage_warehouse_operations", sa.Boolean(), nullable=False
        ),
        sa.Column("can_sync_warehouse_1c", sa.Boolean(), nullable=False),
        sa.Column("can_manage_users", sa.Boolean(), nullable=False),
        sa.Column("can_manage_roles", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###

    conn = op.get_bind()

    admin_id = conn.execute(text(
        """
        INSERT INTO roles (name, is_system, can_view_warehouse, can_manage_warehouse_operations,
                            can_sync_warehouse_1c, can_manage_users, can_manage_roles)
        VALUES ('Администратор', true, true, true, true, true, true)
        RETURNING id
        """
    )).scalar_one()

    engineer_id = conn.execute(text(
        """
        INSERT INTO roles (name, is_system, can_view_warehouse, can_manage_warehouse_operations,
                            can_sync_warehouse_1c, can_manage_users, can_manage_roles)
        VALUES ('Инженер', false, true, false, false, false, false)
        RETURNING id
        """
    )).scalar_one()

    accountant_id = conn.execute(text(
        """
        INSERT INTO roles (name, is_system, can_view_warehouse, can_manage_warehouse_operations,
                            can_sync_warehouse_1c, can_manage_users, can_manage_roles)
        VALUES ('Бухгалтер', false, true, false, false, false, false)
        RETURNING id
        """
    )).scalar_one()

    conn.execute(text("UPDATE users SET role_id = :rid WHERE role = 'ADMIN'"), {"rid": admin_id})
    conn.execute(text("UPDATE users SET role_id = :rid WHERE role = 'ENGINEER'"), {"rid": engineer_id})
    conn.execute(text("UPDATE users SET role_id = :rid WHERE role = 'ACCOUNTANT'"), {"rid": accountant_id})

    op.alter_column("users", "role_id", nullable=False)
    op.drop_column("users", "role")
    op.execute("DROP TYPE IF EXISTS userrole")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'ENGINEER', 'ACCOUNTANT')")
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "ENGINEER", "ACCOUNTANT", name="userrole", create_type=False),
            nullable=True,
        ),
    )

    conn = op.get_bind()
    conn.execute(text(
        """
        UPDATE users SET role = (
            CASE
                WHEN (SELECT is_system FROM roles WHERE roles.id = users.role_id) THEN 'ADMIN'
                WHEN (SELECT name FROM roles WHERE roles.id = users.role_id) = 'Инженер' THEN 'ENGINEER'
                ELSE 'ACCOUNTANT'
            END
        )::userrole
        """
    ))
    op.alter_column("users", "role", nullable=False)

    fk_name = conn.execute(text(
        """
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'users'::regclass AND confrelid = 'roles'::regclass AND contype = 'f'
        """
    )).scalar_one()
    op.drop_constraint(fk_name, "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
